trigger:
- dev

pool:
 vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Development'

steps:
- script: dotnet build --configuraiton $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'