trigger:
- main

pool:
 vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuraiton $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'