trigger:
  branches:
    include:
      - 'multistage-env-pipeline-setup'

name: 'multi-stage-pipeline'

variables:
  buildConfiguration: 'Release'
  releaseBranchName: 'release'
  environment: 'dev'

  namePrefix: 'spacegame'
  vmImageName: 'ubuntu-latest'

  # system.debug: true

  # Azure Resource Variables
  resourceGroupName: $(namePrefix)RG
  location: 'eastus'

  # These will be populated after deployment
  repositoryName: 'tailspin-spacegame-web'

  dotnetSdkVersion: '8.0.x'

parameters:
- name: serviceConnection
  displayName: Azure Service Connection Name
  type: string
  default: azure-subscription-1

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs:
  - job: Build
    displayName: 'Build Job'
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: UseDotNet@2
        displayName: 'Use .NET SDK $(dotnetSdkVersion)'
        inputs:
          packageType: sdk
          version: '$(dotnetSdkVersion)'

      - task: Docker@2
        displayName: 'Build Docker image'
        inputs:
          command: 'build'
          Dockerfile: './Dockerfile'
          repository: '$(repositoryName)'
          tags: |
            $(Build.BuildId)

      - publish: $(Build.ArtifactStagingDirectory)
        displayName: 'Publish Artifact'
        artifact: drop
